### ISSUE TITLE
Unify format for all sectors

### ISSUE THREAD

**Issue by Jeniffere** [GermanZero-de/localzero-generator-core#217]
Refactoring to bring all sectors in a consistent form:

- [x] 1. Make every file `# pyright: strict`

- [x] 2. Remove empty dataclasses and all their references 

```
@dataclass
class Vars0:
    # Used by g, g_storage, g_planning
    pass
```
@bgrundmann: 
> I think Empty and the corresponding member variables should just die. That requires running update_expectations once, but makes the code much nicer.

- [ ] 3. remove unnecessary default values

@bgrundmann: 
> I mildly prefer to only (well mostly only) set default values for member variables if they get computed by __post_init__ from other fields. That way one cannot accidentally forget to initialize one of the variables at the call sites.

- [x] 4. Make every possible dataclass `@dataclass(kw_only=True)`

- [x] 5. Put a comment on top of every sector with a link to the matching part in readthedocs

- [x] 6. Make the interface of each sector more visible by putting it into a separate file like:

i18.py: 
```
@dataclass
class I18:
```

- [ ] 7. Common structure to make the following tow steps explicit:

There are a lot of sectors which consume energy. All these sectors work in two steps:
- calc energy demand / consum --> calc_energy_demand 
- split/divide the calculated demand into several energy sources --> calc_energy_sources 

Idea: create one file for energy_demand.py and one file for energy_sources.py and call the two calc methods in the init of the sector.
See: industry2018
Todo: Talk about a good naming for the two steps.

- [x] 8. Unify imports

with the following rules:
- use relative imports like ..utils instead of generatorcore.utils
- sort imports: external imports, parent package imports (..), current package imports (.)
- import concrete classes like this: from ..residences2018.r18 import R18

**Comment by bgrundmann** [comment]
I agree with all of these. To state the obvious right now none of these should touch Industry (because that would only cause merge failures).

**Comment by bgrundmann** [comment]
> I agree with all of these. To state the obvious right now none of these should touch Industry (because that would only cause merge failures).

And now the changes in industry are merged and everybody should feel free to touch industry again ;-)

**Comment by Jeniffere** [comment]
I started with 6.
See https://github.com/GermanZero-de/localzero-generator-core/tree/extract-main-dataclass-per-sector

**Comment by Jeniffere** [comment]
3. und 7. will be done in: #294
