### ISSUE TITLE
Bug - transport capacity - Dudenhofen

### ISSUE THREAD

**Issue by Jeniffere** [GermanZero-de/localzero-generator-core#313]
python devtool.py run -ags 07338007
liefert AssertionError: We should know have at least as much provided transport capacity as we required initially

**Comment by Jeniffere** [comment]
Error in t.py Z120 bei
` assert (
            required_domestic_transport_capacity_pkm
            <= res.transport.transport_capacity_pkm
        ), "We should know have at least as much provided transport capacity as we required initially"`

**Comment by Jeniffere** [comment]
Das Problem scheint aus rail / bus zu kommen:
`transport_capacity_pkm = div(
            total_transport_capacity_pkm * t18.rail_ppl_distance.transport_capacity_pkm,
            t18.road_bus.transport_capacity_pkm
            + t18.rail_ppl_distance.transport_capacity_pkm
            + t18.rail_ppl_metro.transport_capacity_pkm,
        ) *`

**Comment by Jeniffere** [comment]
Vorbedingung
- data\proprietary\traffic: rail_ppl_elec = 0 und rail_ppl_diesel = 0
- data\public\destatis: metro_mega_km = 0 und bus_mega_km = 0 

Beispiel ags, die die oben beschriebene Vorbedingung erfüllen und ebenfalls zu dem Error führen:
- 07338007 (Dudenhofen)
- 07338006 (Dannstadt-Schauernheim)
- 03360011 (Himbergen)

Beispiel ags, die die oben beschriebene Vorbedingung erfüllen, aber gar keine zulässig ags für die Website darstellen. Sie liefern im Generator eine Row not Found Exception:
- 03156013
- 03156016

**Comment by Jeniffere** [comment]
Lösungsmöglichkeiten:

1. Assertion weglassen (d.h. akzeptieren, dass die required_domestic_transport_capacity_pkm  nicht erreicht wird)
2. Die Daten ändern.
3. Die Berechnung ändern.

**Comment by bgrundmann** [comment]
Hause und ich haben uns das etwas angesehen.  Was ist das Problem?  Die Berechnung geht davon aus das es keine Kommunen gibt bei der der Personen ÖPNV komplett 0 ist (also ist Zustand jeder Mensch fährt PKW es gibt noch nicht mal mehr BUS). 

Genauer gesagt wird aktuell das bestehende ÖPNV Netzwerk insgesamt skaliert aber die relativen Anteile von Bus, Metro, Rail untereinander nicht verändert.  Wenn aber alle 0 sind kommt am Ende nach dem skalieren eben immer noch 0 raus (wir gingen aber davon aus das dann immer wenigstens ein Sektor übernimmt (also meistens Bus)).

Eine mögliche Anpassung wäre es in der Berechnung davon auszugehen das ausschließlich ein komplett neues Busnetzwerk eingesetzt um der Kommune ein ÖPNV Netzwerk zu geben.  (Alternativ könnte man auch sagen die Kommune kommt anteilig sowohl Bus, als auch Metro als auch Fernzug, aber dann ist es schwierig zu wissen nach welchen Anteilen und soweit wir wissen tritt dieses Problem nur bei kleinen Kommunen auf.).

**Comment by bgrundmann** [comment]
Ich habe einen patch von dem Hauke und ich ausgehen das er das richtige macht.  Ich werde nachher noch ein paar tests laufen lassen und ihn danach Leon zum code review geben.
