### ISSUE TITLE
Datenupdate Industrie - Jan

### ISSUE THREAD

**Issue by Jeniffere** [GermanZero-de/localzero-generator-core#407]
- [x] merge initial PR for the 2021 data: https://github.com/GermanZero-de/localzero-data-public/pull/70/files
- [x] Benedikt, Hauke, Jan: check the updated data
- [ ] merge fixes

**Comment by Schmuelling** [comment]
Hauke und Benedikt should check togehter the updated KFI table, e.g. check all AGS ending with -000 (problem Landkreise vs. Kreisfreie Städte), check sum for each Bundesland and Deutschland

**Comment by JanLK** [comment]
Looks good.
PR for the 2021 data: https://github.com/GermanZero-de/localzero-data-public/pull/70/files

As there are no code changes except for replacing the path to the data, the main todos for this issue is checking if the results are plausible and updating the checks if everything looks good.
